# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MPP_IOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
# Pods for MPP_IOS
  pod 'RxCocoa', '~> 5'
  pod 'SwiftyRSA'
  pod 'GzipSwift'


  target 'MPP_IOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MPP_IOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
